import "./globals.css";
import { inter, libreBaskerville } from "@/app/fonts";

import Navigation from "@/components/navigation/Navigation";
import Spacer from "@/components/spacer/Spacer";

export const metadata = {
  title: "Priyana Kale",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${libreBaskerville.className} body`}>
        <Navigation />
        <Spacer />
        {children}
      </body>
    </html>
  );
}
